### PR TITLE
Making scAbsolute compatible with mouse mm10 genome 

### PR DESCRIPTION
**Pull request by AustinReed-1**
Including changes to account for differing genome size, structure, repliChip and blacklisting regions.

### CODE REVIEW

**Comment by leachim** [comment]
I have one issue with this, the source files are completely changed, i.e. I can't see the individual lines that have changed. Do you know why that is? Usually, git is quite good at only highlighting the relevant part of the code that has changed. Did you do some form of reformatting?

**Comment by AustinReed-1** [comment]
That is a pain. I think I may know why. Essentially I had issues originally as I just cloned the main repo and made my changes locally and then found at the end that I couldn't push any changes (even on a new branch). So I then followed your advice to fork first then make a pull request, but I wasn't sure exactly what I had changed on each file so I copied them over into this new forked directory. I thought as it was the same file name etc that github would not realise and simply pick up the parts of each file that I had changed... but maybe not. Do you have an idea of how to resolve that?

**Comment by leachim** [comment]
It's a bit strange, because normally it would figure out the changes, and I assume you only changed a few lines? Did you change anything in terms of formatting? I.e. number of indents or file encoding?

**Comment by AustinReed-1** [comment]
Not that I am aware of. Indents appear to be the same right? But I have no idea how the flie encoding could have changed.

**Comment by leachim** [comment]
Could you try to test this on one file. Just checkout the original file and then use the file from your commit and just compare what's different between them. Just looking at it in vim showed me that one is utf-8 unix and the other utf-8 dos, maybe that's the reason? You can just compare the first few lines with something like head file > A, and use a linux tool like diff to see what's going on.

**Pull request closed without merging**
